[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "neuro_san"
version = "0.0.1"
authors = [
    { name="Dan Fink", email="Daniel.Fink@cognizant.com" }
]
description = "NeuroAI data-driven System for multi-Agent Networks"
readme = "README.md"
requires-python = ">=3.10"
classifiers [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/leaf-ai/neuro-san"
