name: Smoke Tests

on:
  push: 
    branches:
      un-3143_add_smoketest_to_test_infrastructure_part2
  schedule:
    - cron: '0 12 * * *'  # 12:00 PM UTC = 4:00 AM PT (standard)
  workflow_dispatch:      # enables manual triggering

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y shellcheck
          pip install -r requirements-build.txt
          pip install -r requirements.txt

      - name: Show installed packages
        run: pip freeze

      - name: Start agent server service
        shell: bash
        run: |
          apt-get update && apt-get install -y netcat-openbsd procps

          nohup python -m neuro_san.service.agent_main_loop > agent.log 2>&1 &
          echo $! > agent.pid
          sleep 2  # Give it a moment to crash if it's going to
      
          if ! ps -p $(cat agent.pid) > /dev/null; then
            echo "❌ Server process failed to start"
            echo "----- agent.log -----"
            cat agent.log            
            exit 1
      
          echo "✅ Server process started with PID $(cat agent.pid)"
          
          pytest -s --verbose -m "smoke" --timer-top-n 100
          env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            AGENT_TOOL_PATH: "./neuro_san/coded_tools"
            PYTHONPATH: ${{ env.PYTHONPATH }}:"."

      - name: Notify Slack on success
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "✅ *Smoke Tests Passed* for `${{ github.repository }}` on `${{ github.ref_name }}`"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "❌ *Smoke Tests Failed* for `${{ github.repository }}` on `${{ github.ref_name }}`"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
