name: Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'push' && github.ref != 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.base_ref == 'main')
    container:
      image: python:3.12-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y shellcheck
          pip install -r requirements-build.txt
          pip install -r requirements.txt

      - name: Show installed packages
        run: pip freeze

      - name: Run pylint
        run: build_scripts/run_pylint.sh

      - name: Run shellcheck
        run: build_scripts/run_shellcheck.sh

      - name: Run flake8
        run: flake8

      - name: Run pytest with start of server (excluding integration tests & Smoke tests)
        shell: bash
        run: |
          apt-get update && apt-get install -y netcat-openbsd procps curl net-tools

          nohup python -m neuro_san.service.agent_main_loop > agent.log 2>&1 &
          echo $! > agent.pid
          sleep 2

          if ! ps -p $(cat agent.pid) > /dev/null; then
            echo "❌ Server process failed to start"
            echo "----- agent.log -----"
            cat agent.log
            exit 1
          fi

          echo "✅ Server process started with PID $(cat agent.pid)"

          for i in {1..30}; do
            PORT_8080_READY=false
            PORT_30011_READY=false

            if nc -z localhost 8080; then
              PORT_8080_READY=true
            fi

            if nc -z localhost 30011; then
              PORT_30011_READY=true
            fi

            if [ "$PORT_8080_READY" = true ] && [ "$PORT_30011_READY" = true ]; then
              echo "✅ Both ports are ready after awaiting $i seconds"
              break
            fi

            echo "⏳ Waiting for ports 8080 and 30011... ($i/30)"
            sleep 1
          done

          if ! nc -z localhost 8080 || ! nc -z localhost 30011; then
            echo "❌ Timeout: One or both ports failed to open after $i seconds"
            exit 1
          fi

          until curl -s http://localhost:8080/health > /dev/null; do
            echo "Waiting for server health endpoint..."
            sleep 1
          done

          echo "✅ Server is healthy and ready"

          netstat -tuln | grep -E '8080|30011'
          pytest --verbose -m "not integration and not smoke" --timer-top-n 10 -n auto
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AGENT_TOOL_PATH: "./neuro_san/coded_tools"
          PYTHONPATH: ${{ env.PYTHONPATH }}:"."

      - name: Check README renders correctly on PyPI
        run: |
          pip install readme_renderer readme_renderer[md]
          python -m readme_renderer README.md

      - name: Notify Slack on success
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "✅ *Tests Passed* for `${{ github.repository }}` on `${{ github.ref_name }}`"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "❌ *Tests Failed* for `${{ github.repository }}` on `${{ github.ref_name }}`"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
